### ISSUE TITLE
Helping the user bring the right things based on the weather

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-23.APR.PREP.2#4]
- If it's raining, bring an umbrella
- If it's sunny, bring suncream
- If it's cold, bring a coat

**Comment by TynenW** [comment]
Chinat and Tynen will work on this.

**Comment by cyu60** [comment]
@wrussell1999 @grace-omotoso can you specify more about the conditions of "raining", "cold", "sunny"? Does drizzle count as raining? Does snow count as cold? Or should there be a temperature threshold?

**Comment by cyu60** [comment]
Has there been any updates on this issue? @grace-omotoso @TynenW on the conditions that we want to work with? Like if X then bring Y, have we clarified all the conditions?

**Comment by TynenW** [comment]
Hi Chinat,

I think that Grace has updated the issue here: https://github.com/MLH-Fellowship/prep-project-23.APR.PREP.2/pull/10 in regards to the parameters. Let me know if this answers your question!  :)
